export const proyectsarray=[
    {title:"Projects Title 1",
    descipcion:"Some quick example text to build on the card title and make up the bulk of the card's content.",
    dilit:false},
    {title:"Projects Title 2",
    descipcion:"Some quick example text to build on the card title and make up the bulk of the card's content.",
    dilit:false},
    {title:"Projects Title 3",
    descipcion:"Some quick example text to build on the card title and make up the bulk of the card's content.",
    dilit:false},
    {title:"Projects Title 4",
    descipcion:"Some quick example text to build on the card title and make up the bulk of the card's content.",
    dilit:false},
    {title:"Projects Title 5",
    descipcion:"Some quick example text to build on the card title and make up the bulk of the card's content.",
    dilit:false},
    {title:"Projects Title 6",
    descipcion:"Some quick example text to build on the card title and make up the bulk of the card's content.",
    dilit:false},
 ]